spring:
  application:
    name: personal-service

  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: personal